
services:
  bot:
    build: ./go
    container_name: finance_tracker
    image: sukhanoviv/ftbot:latest
    depends_on:
      db:
        condition: service_healthy
      migrate:
    env_file:
      - .env/.dev
    restart: unless-stopped

  db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env/.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3h
      timeout: 30s
      retries: 5
      start_period: 3s

  migrate:
    image: migrate/migrate
    container_name: migrate-db
    volumes:
      - ./migrations:/migrations
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "${DATABASE_URL}"
      - "up"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
