name: CI/CD for a young goodlooking man

on:
  push:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
  
      - name: set up go evn
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
  
      - name: install dependancies
        run: go mod tidy
  
      - name: run tests
        run: cd ./go && go test ./... -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keychan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: deploy to vps
        run: |
          ssh actions@${{ secrets.VPS_HOST }} << 'EOF'
            cd finance_tracker/
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
          
