name: CI/CD for a young goodlooking man 

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
  
      - name: set up go evn
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
  
      - name: install dependancies
        run: cd ./go && go mod tidy
  
      - name: run tests
        run: cd ./go && go test ./... -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: deploy to vps
        run: |
          ssh -v -T root@${{ secrets.VPS_HOST }} << 'EOF'
            echo "Connected to VPS"
            cd finance_tracker/
            git pull origin master
            make compose-restart
          EOF
          
